spring:
  application:
    name: gateway
  config:
    import: "optional:nacos:gateway.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        file-extension: yaml
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/api/log/**
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/api/recommend/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  main:
    web-application-type: reactive

jwt:
  secret: company-user-secret-demo
  expire-minutes: 480
  issuer: gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
