spring:
  application:
    name: video-service
  config:
    import: "optional:nacos:video-service.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/company?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

logging:
  level:
    com.cy: info

video:
  storage:
    location: ${VIDEO_STORAGE_PATH:videos}
    media-prefix: /api/video/media
