spring:
  application:
    name: recommend-service
  config:
    import: "optional:nacos:recommend-service.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/company?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  rabbitmq:
    host: localhost
    port: 5672
    username: itheima
    password: 123456
    virtual-host: /hmall

server:
  port: 8085

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
